### ISSUE TITLE
Modules not updating

### ISSUE THREAD

**Issue by JayDee2202** [dapor2000/IPS_MODULES#9]
Hello!

After updating to the master branch (and correcting the file path) the IPS module doesn't get data from the station. Shown error in the log and by clicking on "show data"/"get data":
> <b>Fatal error</b>:  Call to undefined function NAW2_SaveData() in <b>-</b> on line <b>2</b><br />

![mstsc_2016-12-15_18-04-09](https://cloud.githubusercontent.com/assets/15029826/21234017/949896ea-c2f1-11e6-93fe-1ec81db1f44e.png)

**Comment by dapor2000** [comment]
give it a try

**Comment by JayDee2202** [comment]
Works fine now, thanks!
